### PR TITLE
Compact version in url

### LINKED ISSUE #179: Visiting older version of docs while on a newly introduced class causes errors that aren't handled
Visit `ember/2.12.0/classes/Ember.Engine` and switch version on the left to any 1.x version. The app immediately try to makes a request for a class that doesn't exist so the app is left in a broken state.

### PR DESCRIPTION
**Pull request by sivakumar-kailasam**
Fixes #179

### CODE REVIEW

File: config/target.js [hunk 1]
```diff
@@ -1,9 +1,19 @@
...
+  'last 1 Chrome versions',
+  'last 1 Firefox versions',
+  'last 1 Safari versions'
+];
+
+if (process.env.EMBER_ENV === 'development' || process.env.EMBER_ENV === 'test') {
+  browsers = [
     'last 1 Chrome versions',
-    'last 1 Firefox versions',
-    'last 1 Safari versions'
```
Comment (toddjordan) [inline config/target.js]: no safari?

**Comment by toddjordan** [comment]
awesome!

File: config/target.js (hunk 1 above)
Comment (sivakumar-kailasam) [inline config/target.js]: I assumed all of us favor chrome during development 🙈
